### PR TITLE
Proof issue #5 - adapt tox to build example for several sphinx versions

### PR DESCRIPTION
**Pull request by SteinHeselmans**
Removed sphinx<1.3 from tox due to template not available at that time
(2014).

Proving issue #5

### CODE REVIEW

**Comment by Letme** [comment]
Umn, it is still failing?

May I suggest
```
if sphinx.__version__ < '1.6.0':
    old crap we had
else:
   fixes to get it working with 1.6
```

**Comment by SteinHeselmans** [comment]
Umn, this makes the build fail, as it is the proof that bug #5 is valid, and should be seen as an improvement for our CI test cases.

The actual fix for #5 is in #6 , do i propose to first merge #6 and then this one #7, in order to don't have a failing CI on master branch.

V1.4.0 is hidden on pypi, making V1.3.0 the default to download. I'll make a  V1.4.1 after this bug #5 is fixed.

**Comment by Letme** [comment]
Yeah  sure, merge first #6 then merge master into #7 and after checks have passed merge this in.

**Comment by SteinHeselmans** [comment]
status: #6 is merged to master, now merged master into this one (#7). Ready for merge after CI check.

**Pull request merged**
