### PR TITLE
Fix some quality-of-life issues with item-piechart

### LINKED ISSUE #321: Confusing behavior of item-piechart colors argument
The `colors` argument to the `item-piechart` directive contains some (undocumented) logic to intelligently allocate colors around empty categories, allowing the user to provide fewer color arguments than what's called for in the documentation:

> a color for each regex in id_set, followed by as many relationships/colors given for [...] the \<\<attribute>> option

However, it seems the corresponding logic is not quite correct, as evidenced by the following MRE:

```
.. item:: RQT-1 UNCOVERED

.. item:: RQT-2 COVERED
    :validated_by: TC-2

.. item:: TC-2

.. item:: RQT-3 FAILED
    :validated_by: TC-3

.. item:: TC-3
    :tested_by: TR-3

.. item:: TR-3
    :result: FAILED

.. item:: RQT-4 PASSED
    :validated_by: TC-4

.. item:: TC-4
    :tested_by: TR-4

.. item:: TR-4
    :result: PASSED

.. item-piechart::
    :id_set: RQT- TC- TR-
    :label_set: UNCOVERED, COVERED, EXECUTED
    :sourcetype: validated_by
    :targettype: tested_by
    :result: FAILED, PASSED
    :colors: grey yellow red green
```

In that example, the `EXECUTED` group is empty, as all `TR`s have a `PASSED`/`FAILED` value. One would then expect four color arguments to be sufficient. Attempting to build said MRE, however, will result in the following warning:

```
WARNING: item-piechart contains 4 slices: 1 color(s) will be reused
```

And the following pie chart:

image

One could argue that even if the feature worked as expected, the correct number of color arguments should never depend on a category being empty, as that is not necessarily under the user's control (as in the `PASSED`/`FAILED` example above).

### PR DESCRIPTION
**Pull request by gcrabbe**
This PR fixes the following perceived shortcomings of the `item-piechart` directive:

* Fix the reported values in the error message for the wrong number of color arguments when some of the labels are empty. Fixes #321.
* Make the default behavior to hide coverage statistics unless the `stats` flag is provided (c.f. #323), as is done with other directives such as `item-matrix`.

As per the discussion below, this PR introduces breaking changes and should be scheduled for the next major release.

### CODE REVIEW

**Comment by JasperCraeghs** [comment]
> Fix the reported values in the error message for the wrong number of color arguments when some of the labels are empty.

I understand why you want to change this. The current implementation is intentional, however. No warning is reported when the user has not defined a color for every possible slice but as long as the number of slices that are generated is not greater than the number of colors defined, no warning is generated because no color is reused.

I'm not opposed to changing this behavior when increasing the major version number but then the warning message should be updated to `item-piechart can contain up to X slices but you only specified Y colors: some colors may be reused`

**Comment by gcrabbe** [comment]
In that case, the current implementation is flawed, because I was in fact seeing the warning in a situation where I had five categories, one of which was empty, but only provided four colors. So the error message was:
```
WARNING: item-piechart contains 4 slices: 1 color(s) will be reused

**Comment by JasperCraeghs** [comment]
The warning stated that 1 color was reused when in fact this was not the case. Is that what you're saying? I have not been able to reproduce that corner case. If the current implementation is indeed flawed because of this, I am in favor of adding your change to the next major version.

Regarding the new `:stats:` flag, I want to add the flag to the directive but not let it affect the output yet. Report a warning first when the flag is not used and mention that the user has to add this flag if they want to keep the statistics when upgrading to the next major version (v10).

**Comment by gcrabbe** [comment]
> The warning stated that 1 color was reused when in fact this was not the case. Is that what you're saying?

It was being reused when it shouldn't have been. I have created #321 with some additional context.

> Report a warning first when the flag is not used and mention that the user has to add this flag if they want to keep the statistics when upgrading to the next major version (v10).

Sure.

**Comment by JasperCraeghs** [comment]
I reverted 85ee0641e412d6fad182ba6d83a32a28ffab02e3 in favor of #337. The difference is that no empty paragraph node will be added.

**Review by JasperCraeghs — APPROVED** [review]

**Pull request merged**
