### PR TITLE
statistics for item-matrix, admonition title for all directives

### PR DESCRIPTION
**Pull request by SteinHeselmans**
Add some statistics about coverage at the top of an item-matrix

### CODE REVIEW

**Comment by Letme** [comment]
Waw this simple. Then you can also add a graph as easy as that probably (`:stats: graph` flag?)

**Comment by SteinHeselmans** [comment]
yes, something like that would be possible. Although i was thinking about defining a special 'item-piechart' directive with some attributes. Then we can generate those charts in an overview page, and don't have to go through the tables when we just want the percentages (managers/auditors first view).

**Comment by SteinHeselmans** [comment]
improved in b6eb6b3: the item-matrix displays its title in an admonition. That is the docutils object which is rendered to the blue bar with a title in it, as we do for items. This makes the rendering more consistent, i will adapt the rendering of item-list and item-tree accordingly...

**Comment by SteinHeselmans** [comment]
Generalized the admonition style for titles of all directives in 29d0617

**Comment by SteinHeselmans** [comment]
Ready for review/merge :wink:

**Comment by Letme** [comment]
Agreed on the special item to provide more attributes and make an overview page.

**Pull request merged**
